# !!!!!!!!!!!!!!!!!!!!!!!
# !!!!    WARNING    !!!!
# !!!!!!!!!!!!!!!!!!!!!!!
# PyYAML resolves scientific notation numbers as strings-
# e.g. 1.6e3 is interpreted as '1.6e3', not 1600. These numbers should
# be expanded (see bc_Te_max)

# Basic Parameters ##
# Units MUST exactly match astropy.units counterparts
# http://docs.astropy.org/en/stable/units/
global:
    flux_unit: "erg cm-2 s-1 AA-1"
    wl_unit: "AA"

narrow_lines:
    boxcar_width: 5
    width_min: 10. # km/s
    width_max: 700. # km/s
    amp_min: 0.
    amp_max: "max_flux" #max_flux or fnw
    center_size: 5
    wavelengths: {"CIV_1549": 1549.05, "OIII]_1664": 1664.15, "AlII_1670": 1670.79, "NIII]_1750": 1750.46, "SiII_1813": 1813.98, "NII]_2141": 2141.36, "CII]_2326": 2326.58, "[OIII]_5006": 5006.84, "[NI]_5199": 5199.82, "[CaV]_5309": 5309.18, "[OI]_6363": 6363.78, "OI_8446": 8446.5, "[SIII]_9086": 9068.9}

## Host Galaxy ##
host_galaxy:
    boxcar_width: 5
    hg_no_templates: 2
    hg_models: "../Data/HostModels"
    hg_norm_min: 0
    hg_norm_max: "max_flux"
    hg_stellar_disp_min: 30. # km/s. Must be dispersion, not FWHM
    hg_stellar_disp_max: 500. # km/s. Must be dispersion, not FWHM
    hg_template_stellar_disp: 0.0
    hg_kernel_size_sigma: 10 # pixels

## Boxcar width to use when calculating running mean ##
boxcar_width: 5

## PowerLawComponent parameters ##
## WARNING: If using broken power law, need to have estimation of priors otherwise model cannot converge ##
power_law:
    boxcar_width: 5
    broken_pl: False
    pl_slope_min: -3.
    pl_slope_max: 3.
    pl_norm_min: 0.
    pl_norm_max: "max_flux"
    pl_wave_break_min: "min_wl"
    pl_wave_break_max: "max_wl"

## Balmer Continuum ##
balmer_continuum:
    bc_line_type: "lorentzian" #or "gaussian"
    bc_lines_min: 3. #km/s
    bc_lines_max: 400. #km/s
    bc_norm_min: 0.
    bc_norm_max: "bcmax_flux" # Balmer Continuum max flux
    bc_Te_min: 5000.
    bc_Te_max: 20000.
    bc_tauBE_min: 0.1
    bc_tauBE_max: 2.
    bc_loffset_min: -10.
    bc_loffset_max: 10.
    bc_lwidth_min: 100.
    bc_lwidth_max: 10000.
    bc_logNe_min: 2
    bc_logNe_max: 9


## Fe Component ##
fe_component:
    boxcar_width: 10
    fe_templates: "../Data/FeModels"
    fe_template_width: 900. #km/s
    fe_norm_min: 0.
    fe_norm_max: "fnw" #max_flux or fnw
    fe_width_min: 901. # km/s (FWHM)
    fe_width_max: 10000. # km/s (FWHM)
    fe_line_type: "gaussian" # or "lorentzian"
    fe_kernel_size_sigma: 3 # pixels

## Flux Conserving Binning ##
rebin_spec: False

## Testing ##
testing:
    wl_min: 1000
    wl_max: 10000
    wl_step: 0.5
